# Generated by Django 5.1.2 on 2024-11-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pan_de_reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
