# Generated by Django 5.1.3 on 2024-11-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pan_de_reserve', '0002_bakeryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格'),
        ),
    ]
