# Generated by Django 5.1.3 on 2024-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pan_de_reserve', '0004_reservationdetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
